### ISSUE TITLE
Rock Paper Scissor game in differents language

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2022#118]
If someone can add this game in different language (Py3 already done)

**Comment by ricveal** [comment]
I would like to add implementations for this algorithm in Javascript, Typescript and Java.

**Comment by Ramprashanth1** [comment]
I can do this in C/C++, can you assign this to me

**Comment by Ramprashanth1** [comment]
Created Pull Request , File name: rpprscs(c++).cpp
Is this enough to be accepted for hacktoberfest2021 or am I missing something
