### ISSUE TITLE
Rod Cutting Problem

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2022#120]
Given a rod of length n, and an array that contains the prices of all the pieces smaller than n, determine the maximum profit you could obtain from cutting up the rod and selling its pieces.
any language

**Comment by udita-22** [comment]
Hey can you assign me this issue?

**Comment by udita-22** [comment]
Hey @Knackie I have added algorithm of this problem in c language . Kindly review my pr
Thank you

**Comment by Knackie** [comment]
> pr

Where is the PR ?

**Comment by udita-22** [comment]
@Knackie I have made the required changes in pr. Kindly review it.
#206
