### ISSUE TITLE
Top View Of Binary Tree in Python

### ISSUE THREAD

**Issue by Sprokr** [Knackie/algorithmshacktoberfest2022#215]
The Problem statement - 
Given a binary tree, return the nodes visible from the top in the same order from left to right.

Language - Python

Ex - 
```
        1
    /      \
   2        3
 /   \    /   \
4     6    9    10
```
       

Output: 4  2  1  3  10

**Comment by Knackie** [comment]
Could you implementate that ?

**Comment by Sprokr** [comment]
Yes, Adding it.
