### ISSUE TITLE
Make Minimum in array in Python2

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2022#219]
Hi,
Could you make the algorithm for minimum in array in python 2?
https://github.com/Knackie/algorithmshacktoberfest2022/tree/main/algorithms/ar-min

**Comment by Anmol-Prasad** [comment]
Hi I would love to contribute to your project. Would appreciate if you can assign this project to me

**Comment by Knackie** [comment]
Yes, thanks you !

**Comment by Anmol-Prasad** [comment]
Hi Knackie! I have completed the code for this problem in python 2 . Since we use python3 nowadays, do you need the code for python3 as well? Just few important changes in the syntax and it would be ready to rock

**Comment by Knackie** [comment]
yes, you can add your code for python 3 :) Thanks

**Comment by Anmol-Prasad** [comment]
Hi! I have added the codes you may check it in the PR
