### ISSUE TITLE
Bogosort algorithms

### ISSUE THREAD

**Issue by ryguigas0** [Knackie/algorithmshacktoberfest2022#245]
I would like to add bogosort algorithms for:

- Java
- Elixir
- Javascript
- Typescript

Could you assign me this issue?

**Comment by MoonLGH** [comment]
whoops, i already got bogo for ts #254

**Comment by Knackie** [comment]
Yes thanks

**Comment by ryguigas0** [comment]
Opened #284, there was already an Java implementation when I created the PR, warn me if I should use the later or mine
