### ISSUE TITLE
Add CPU scheduling algorithms

### ISSUE THREAD

**Issue by arib-ashhar** [Knackie/algorithmshacktoberfest2022#279]
I would like to add CPU scheduling algorithms in C++
@Knackie Could you assign me this issue?

**Comment by Animesht1008** [comment]
hi! @Knackie, i would love to work on this issue under the tag of hacktoberfest 2022. so can you please assign it to me

**Comment by Animesht1008** [comment]
hi @Knackie actually i wanted to ask that where i should put my folder for the above issue ?

**Comment by Sandyy07** [comment]
Hi @Knackie , Kindly please assign me this issue.
