### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by Knackie** [Knackie/algorithmshacktoberfest2022#301]
I've some troubles with this repos : 
- somes files are not in the good folder
- the readme is not totally updated
If anyone can fix it, and somes readme in subfolder would be very nice

**Comment by Shivam164** [comment]
I want to work on this, please assign this to me.

**Comment by Shivam164** [comment]
@Knackie

**Comment by Knackie** [comment]
> @Knackie

Done

**Comment by MaheshPrayaga** [comment]
Hey, is this done? or can i raise a pull request?

**Comment by Shivam164** [comment]
@MaheshPrayaga 
I am working on this.

**Comment by MaheshPrayaga** [comment]
okay, alright @Shivam164

**Comment by COdErJ26** [comment]
is this still open to work ?
