### ISSUE TITLE
Add Boyer Moore Algorithm in Java

### ISSUE THREAD

**Issue by AaryanSingh0017** [Knackie/algorithmshacktoberfest2022#309]
I would like to add Boyer Moore Algorithm for:

- JAVA
Could you assign me this issue?

@Knackie

**Comment by Knackie** [comment]
Yes ofc

**Comment by MaheshPrayaga** [comment]
hey, @Knackie i don't get the concept of assigning. what's the difference between someone raising a direct PR and one raising a PR after getting assigned with an issue?

**Comment by Sandyy07** [comment]
Hi @Knackie , Kindly please assign me this issue.
