### ISSUE TITLE
Add left View of binary tree in C

### ISSUE THREAD

**Issue by himanshuaggar** [Knackie/algorithmshacktoberfest2022#316]
hey, I want to add a left view of the binary tree in C language, Please assign me this issue @Knackie

**Comment by Knackie** [comment]
Done @himanshuaggar

**Comment by Sandyy07** [comment]
Hi @Knackie , Kindly please assign me this issue.

**Comment by himanshuaggar** [comment]
Hey, i have made the changes in #330
