### ISSUE TITLE
Add CPP Solutions For Linked list

### ISSUE THREAD

**Issue by kashyapkumar-pdf** [Knackie/algorithmshacktoberfest2022#320]
Assign this task to me.

**Comment by Knackie** [comment]
Yes

**Comment by Sandyy07** [comment]
Hi @Knackie , Kindly please assign me this issue.

**Comment by Animesht1008** [comment]
hi @Knackie Can you assign this issue to me

**Comment by RishabhSharma96** [comment]
@Knackie Kindly assign me this issue.

**Comment by Knackie** [comment]
Done

**Comment by AshishSharma1203** [comment]
kindly assign this issue to me also.

**Comment by RishabhSharma96** [comment]
@Knackie i have added algos you messaged me to follow this. Kindly review and merge

**Comment by Knackie** [comment]
>  kindly assign this issue to me also. 

Done

**Comment by akshaygidwani404** [comment]
Hi @kashyapkumar-pdf! I would love to contribute to this issue. Please do assign it to me.

**Comment by gauriimaheshwarii** [comment]
Can I work on this issue?

**Comment by anupeshverma** [comment]
kindly assign this issue to me.
