### ISSUE TITLE
To add DNF Algo

### ISSUE THREAD

**Issue by AshishSharma1203** [Knackie/algorithmshacktoberfest2022#340]
I want to add Dutch National Flag Algorithm.

**Comment by Knackie** [comment]
Go for it

**Comment by gauriimaheshwarii** [comment]
Please assign this issue to me.

**Comment by AshishSharma1203** [comment]
I have added the DNF Algo in the respective repo and had created a pull request for it. Please review it and merge it. 

> Go for it

**Comment by AshishSharma1203** [comment]
Closed as issue solved by #368
