### ISSUE TITLE
Prim's Algorithm in C

### ISSUE THREAD

**Issue by PalaVenkiReddy** [Knackie/algorithmshacktoberfest2022#342]
I want to contribute Prim's Algorithm in C language. Please assign this issue to me @Knackie

**Comment by Knackie** [comment]
yes sure !

**Comment by iamrishabhjoshi** [comment]
I want to contribute @Knackie . Please accept my PR.

**Comment by gauriimaheshwarii** [comment]
Can I contribute to this issue?

**Comment by Sandyy07** [comment]
Hi , Kindly please assign this issue to me .
