### ISSUE TITLE
added Greddy Algorithm in Python3

### ISSUE THREAD

**Issue by TeddyFirman** [Knackie/algorithmshacktoberfest2022#346]
Hi, I want to contribute Greddy Algorithm in Python3 language. Please assign this issue to me @Knackie, Thank You

**Comment by Sandyy07** [comment]
Hi @Knackie . Kindly please assign me this issue.

**Comment by Knackie** [comment]
yes sur

**Comment by TeddyFirman** [comment]
thanks

**Comment by gauriimaheshwarii** [comment]
Please assign this issue to me.
