### ISSUE TITLE
Dynamic Programming: Longest Increasing Subsequence

### ISSUE THREAD

**Issue by aryangupta899** [Knackie/algorithmshacktoberfest2022#374]
Hi, can you please assign me to this issue?

**Comment by satyamgupta461** [comment]
Hey @aryangupta899. I have quite a good hands-on knowledge of JAVA and I have done this Longest Increasing code. Please appoint me to the project.

**Comment by aryangupta899** [comment]
> Hey @aryangupta899. I have quite a good hands-on knowledge of JAVA and I have done this Longest Increasing code. Please appoint me to the project.

Hi @satyamgupta461 I myself wanted to be assigned and work on this. I'm not the owner of the repo, so I can't assign you.

**Comment by satyamgupta461** [comment]
Sorry @aryangupta899 wrong mention.

**Comment by satyamgupta461** [comment]
Hey. I have quite a good hands-on knowledge of JAVA and I have done this Longest Increasing code. Please appoint me to the project.

**Comment by Knackie** [comment]
> Hi, can you please assign me to this issue?

Done

**Comment by aryangupta899** [comment]
Sent a pull request
#401
