### ISSUE TITLE
Adding Do Not Be Distracted [Codeforces] solution - JAVA programming language solution.

### ISSUE THREAD

**Issue by codedmachine111** [Knackie/algorithmshacktoberfest2022#378]
Hello @Knackie . I would love to contribute by adding the solution for **Do Not Be Distracted** [Codeforces] problem, in **JAVA** programming language. The algorithm is Accepted on Codeforces and has an execution time of 140ms. Kindly assign me this issue.

**Comment by satyamgupta461** [comment]
Hey @codedmachine111. I have quite a good hands-on knowledge of JAVA. Please appoint me to the project.

**Comment by Knackie** [comment]
Done
