### ISSUE TITLE
Bucket sort using c

### ISSUE THREAD

**Issue by YosoyAryan** [Knackie/algorithmshacktoberfest2022#411]
Please assign the issue to me, I opened it to contribute the implementation of bucket sort using C.

**Comment by dariocast** [comment]
I can work on this, assign me

**Comment by anupeshverma** [comment]
!assign

**Comment by anupeshverma** [comment]
Assign this to me i have contributed bucket sort in cpp

**Comment by Knackie** [comment]
Done

**Comment by dariocast** [comment]
My PR #419 closes this issue
