### ISSUE TITLE
Quick Sort using C++

### ISSUE THREAD

**Issue by Animesht1008** [Knackie/algorithmshacktoberfest2022#91]
Hi @Knackie ,
I would like to work on this operation as a part of Hacktoberfest 2021 so please can you assign me this issue.
Thank you!

**Comment by Knackie** [comment]
Hi !
Good luck, i've assigned you :)

**Comment by Knackie** [comment]
and if you want chess, you can add me : RendezMoiKnacki 👍🏼

**Comment by Animesht1008** [comment]
okay @Knackie i have given a request to add you
